networks:
  terrarium_network:
    external: true

services:
  mc-terrarium:
    image: cloudbaristaorg/mc-terrarium:0.0.22
    container_name: mc-terrarium
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - terrarium_network
    ports:
      - target: 8055
        published: 8055
        protocol: tcp
    env_file:
      - ./secrets/credentials             # AWS credential
      - ./secrets/credential-azure.env    # Azure credential
      - ./secrets/credential-alibaba.env  # Alibaba credential
      - ./secrets/credential-tencent.env  # Tencent credential
      - ./secrets/credential-ibm.env      # IBM credential
      - ./secrets/credential-ncp.env      # NCP credential
    volumes:
      - ./secrets/credential-gcp.json:/app/secrets/credential-gcp.json:ro # GCP credential
      - ./container-volume/mc-terrarium-container/.terrarium:/app/.terrarium
      - /etc/ssl/certs:/etc/ssl/certs:ro
    environment:
      - TERRARIUM_ROOT=/app
      # - TERRARIUM_SELF_ENDPOINT=localhost:8055
      # - TERRARIUM_API_ALLOW_ORIGINS=*
      # - TERRARIUM_API_AUTH_ENABLED=true
      # - TERRARIUM_API_USERNAME=default
      # - TERRARIUM_API_PASSWORD=$$2a$$10$$cKUlDfR8k4VUubhhRwCV9.sFvKV3KEc9RJ.H8R/thIeVOrhQ.nuuW
      # - TERRARIUM_LOGFILE_PATH=/app/log/terrarium.log
      # - TERRARIUM_LOGFILE_MAXSIZE=1000
      # - TERRARIUM_LOGFILE_MAXBACKUPS=3
      # - TERRARIUM_LOGFILE_MAXAGE=30
      # - TERRARIUM_LOGFILE_COMPRESS=false
      - TERRARIUM_LOGLEVEL=info
      # - TERRARIUM_LOGWRITER=both
      # - TERRARIUM_NODE_ENV=production
      # - TERRARIUM_AUTOCONTROL_DURATION_MS=10000
    healthcheck: # for MC-Terrarirum
      test: ["CMD", "curl", "-f", "http://localhost:8055/terrarium/readyz"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 10s
