services:
  mc-terrarium:
    image: cloudbaristaorg/mc-terrarium:edge
    container_name: mc-terrarium
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
    env_file:
      - ./secrets/credentials           # AWS credentials
      - ./secrets/credential-azure.env  # Azure credentials
    volumes:
      - ./secrets:/app/secrets:ro       # GCP credentials
    environment:
      # - TERRARIUM_ROOT=/app
      # - TERRARIUM_SELF_ENDPOINT=localhost:8888
      # - TERRARIUM_API_ALLOW_ORIGINS=*
      # - TERRARIUM_API_AUTH_ENABLED=true
      # - TERRARIUM_API_USERNAME=default
      # - TERRARIUM_API_PASSWORD=default
      # - TERRARIUM_LOGFILE_PATH=/app/log/terrarium.log
      # - TERRARIUM_LOGFILE_MAXSIZE=1000
      # - TERRARIUM_LOGFILE_MAXBACKUPS=3
      # - TERRARIUM_LOGFILE_MAXAGE=30
      # - TERRARIUM_LOGFILE_COMPRESS=false
      - TERRARIUM_LOGLEVEL=debug
      # - TERRARIUM_LOGWRITER=both
      # - TERRARIUM_NODE_ENV=production
      # - TERRARIUM_AUTOCONTROL_DURATION_MS=10000
    healthcheck: # for MC-Terrarirum
      test: [ "CMD", "curl", "-f", "http://localhost:8888/terrarium/readyz" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
