volumes:
  etc_wireguard:

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:13
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - target: ${WG_PORT:-51820}
        published: ${WG_PORT:-51820}
        protocol: udp
      - target: ${WG_EASY_PORT:-51821}
        published: ${WG_EASY_PORT:-51821}
        protocol: tcp
    restart: unless-stopped
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi, ja, si)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${PUBLIC_IP?Public IP must be set}

      # (needs double $$, hash of 'multicloud123!'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      - PASSWORD_HASH=${WG_EASY_PASSWORD_HASH:-$$2a$$12$$iSCQRRM8cJxXnCNbWWM.1.4rHSEXloWPVy6XXei0TXfMWhDsSsTVq}
      - PORT=${WG_EASY_PORT:-51821}
      - WG_PORT=${WG_PORT:-51820}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS:-10.1.0.x} # Clients IP address range
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS:-8.8.8.8}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS:-10.0.0.0/8}

      # Optional:
      # - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG # (needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
      # - WG_ENABLE_ONE_TIME_LINKS=true
      # - UI_ENABLE_SORT_CLIENTS=true
      # - WG_ENABLE_EXPIRES_TIME=true
      # - ENABLE_PROMETHEUS_METRICS=false
      # - PROMETHEUS_METRICS_PASSWORD=$$2a$$12$$vkvKpeEAHD78gasyawIod.1leBMKg8sBwKW.pQyNsq78bXV3INf2G # (needs double $$, hash of 'prometheus_password'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
